AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy MySQL RDS in Private Subnet

Parameters:
  DBSubnet1:
    Type: String
  DBSubnet2:
    Type: String
  DBUsername:
    Type: String
  DBPassword:
    Type: String
  DBVpcSecurityGroup:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: MyAppDB
      Engine: mysql
      EngineVersion: 5.7.44
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      VPCSecurityGroups:
        - !Ref DBVpcSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
